name: JR Assemble

on:
  workflow_call:

jobs:
  assemble:
    runs-on: ubuntu-latest
    name: Assemble
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download fatjar
        uses: actions/download-artifact@v3
        with:
          name: fatjar
          path: build/libs
      - name: JR Assemble
        uses: jreleaser/release-action@v2
        with:
          version: early-access
          arguments: assemble
      - uses: actions/upload-artifact@v3
        with:
          name: javaarchive
          path: out/jreleaser/assemble/spring-cli/java-archive/*.zip
          retention-days: 1
