name: JR Assemble JLink

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      version:
        required: true
        type: string


jobs:
  assemble:
    runs-on: ubuntu-latest
    name: Assemble
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - name: Download fatjar
        uses: actions/download-artifact@v3
        with:
          name: fatjar
          path: build/libs
      - name: Jdks
        shell: bash
        run: ./gradlew copyJdksFromCache setupJdks
      - name: JR Assemble
        uses: jreleaser/release-action@v2
        with:
          arguments: assemble --assembler jlink
        env:
          JRELEASER_PROJECT_VERSION: ${{ inputs.version }}
      - name: Upload jlink
        uses: actions/upload-artifact@v3
        with:
          retention-days: 1
          name: jlink
          path: |
            out/jreleaser/assemble/jreleaser-cli-jlink/jlink/*.zip
