name: Early Access

on:
  workflow_dispatch:

jobs:

  precheck:
    uses: ./.github/workflows/jr-version.yml
    with:
      version:
  step1:
    needs: [precheck]
    uses: ./.github/workflows/jr-build.yml
    with:
      ref: ${{ needs.precheck.outputs.ref }}
  step2:
    needs: [precheck,step1]
    uses: ./.github/workflows/jr-assemble.yml
    with:
      ref: ${{ needs.precheck.outputs.ref }}
      version: ${{ needs.precheck.outputs.version }}
  step3:
    needs: [precheck,step2]
    uses: ./.github/workflows/jr-release.yml
    secrets: inherit
    with:
      ref: ${{ needs.precheck.outputs.ref }}
      version: ${{ needs.precheck.outputs.version }}

