name: JR Release

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    name: JR Release
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - name: Download fatjar
        uses: actions/download-artifact@v3
        with:
          name: fatjar
          path: build/libs

      - name: Download javaarchive
        uses: actions/download-artifact@v3
        with:
          name: javaarchive
          path: out/jreleaser/assemble/spring-cli/java-archive

      - name: Release
        uses: jreleaser/release-action@v2
        with:
          arguments: full-release
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_PROJECT_VERSION: ${{ inputs.version }}
